package Camera;

import java.util.List;

/**
 * Class describing a camera.
 * Camera holds relevant information about data generated by a camera
 */
public class Camera {
	private List<CameraObject> cameraObjectList;
}
